### ISSUE TITLE
Breach of license terms

### ISSUE THREAD

**Issue by lfirek** [celso-henrique/redux-api-middleware-native#1]
Hello,

You fork my repo https://github.com/lfirek/redux-native-api-middleware but look at license terms https://github.com/lfirek/redux-native-api-middleware/blob/master/LICENSE . 

You need write I'm author of this software.

**Comment by celso-henrique** [comment]
I changed many things and it isn't the same code anymore, my middleware got many differences like the usage way, meta and possibility to use a custom handler for payload and meta.

**Comment by lfirek** [comment]
> I changed many things

You forked my project and change AUTHOR and now you are admiting it. In license terms are no specific how many code you need change to delete author informations.

I reported this in github.com and if you do not delete this project or add author to project I will request DMCA delete. However in this issue you admitting you are steal my work.
