### ISSUE TITLE
Breach of license terms v2 Celso Henrique is thief

### ISSUE THREAD

**Issue by lfirek** [celso-henrique/redux-api-middleware-native#2]
You write on issue https://github.com/celso-henrique/redux-api-middleware-native/issues/1

> I changed many things

You forked my project and change AUTHOR and now you are admiting it. In license terms are no specific how many code you need change to delete author informations.

I reported this in github.com and if you do not delete this project or add author to project I will request DMCA delete. However in this issue you admitting you are steal my work.

**Comment by celso-henrique** [comment]
Closing.. this isn't the same project, same concept but different codes. Feel free to request DMCA, there is many projects that use this concept of middleware, you wont create it.   #1
